apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: metabloit/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: metabloit/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.tsx'
        dest: .
  - image: metabloit/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: metabloit/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: metabloit/nats-init
    context: nats-initializer
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: metabloit/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
  - image: metabloit/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*
  - ./infra/k8s-dev/*
deploy:
  kubectl: {}
