apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  namespace: default
spec:
  ports:
  - port: 3000
    targetPort: 3000
  clusterIP: None
  selector:
    app: grafana
    namespace: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-proxy
  namespace: default
spec:
  ports:
  - port: 9090
    targetPort: 9090
  clusterIP: None
  selector:
    app: grafana
    namespace: ingress-nginx
