apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-depl
  template:
    metadata:
      labels: 
        app: expiration-depl
    spec:
      initContainers:
      - name: wait-for-nats
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup nats-srv.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nats-srv; sleep 2; done"]
      - name: wait-for-nats-init
        image: busybox
        command: ['sh', '-c', "until nslookup nats-init-srv.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nats-init-srv; sleep 2; done"]
      containers:
      - name: expiration-depl
        image: metabloit/expiration:latest
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: REDIS_HOST
          value: expiration-redis-srv
