name: Orders Deployment
run-name: ${{ github.actor }} deploying orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  orders-deployment:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} has been cloned to the runner."
      - name: Build image and login to Docker Hub
        working-directory: ./orders
        run: |
          docker build -t metabloit/orders .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to Docker Hub
        run: docker push metabloit/orders
      - name: Deploy the service
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Setting up kubeconfig
        run: doctl kubernetes cluster kubeconfig save e19d9368-2922-4d57-99a8-3315b0b950eb
      - name: Making sure up-to-date image is used
        run: kubectl rollout restart deployment orders-depl
